name: almajlis
description: AlMajlis

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 0.11.1+8
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  jaguar_retrofit: null
  intl: ^0.16.1
  shared_preferences: ^0.5.7+3
  loading: ^1.0.2
  flutter_udid: null
  path_provider: null
  permission_handler: 4.4.0
  fluttertoast: ^4.0.1
  country_code_picker: null
  otp_text_field: null
  gradient_widgets: null
  image_picker: null
  dio: null
  path: null
  video_thumbnail: null
  video_player: null
  url_launcher: null
  file_picker: 1.13.3
  timeago: null
  firebase_messaging: null
  flutter_webview_plugin: null
  flutter_event_bus: null
  sms_autofill: ^1.2.7
  # sms: ^0.2.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_places_dialog: ^1.0.5
  pull_to_refresh: ^1.6.1
  http: ^0.12.0+4
  photo_view: null
  geolocator: null
  google_maps_flutter: ^0.5.30
  google_map_location_picker: ^3.3.3
  get_it: null
  cached_network_image: null
  firebase_dynamic_links: ^0.5.0+11
  clipboard_manager: null
  share: null
  # agora_rtc_engine: ^3.0.1-dev.7
  agora_rtc_engine: ^1.0.15
  flutter_linkify: null
  flutter_image_compress: null
  pin_code_fields: null
  flutter_cupertino_date_picker:
    git: https://github.com/daveleenew/flutter-cupertino-date-picker.git
  flutter_native_timezone: ^1.0.4
  in_app_purchase: ^0.3.4+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  jaguar_retrofit_gen: null
  jaguar_serializer_cli: null
  build_runner: null
  flutter_launcher_icons: ^0.7.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "drawables/ic_launcher.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - drawables/
    - drawables/2x/
    - drawables/3x/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProximaNovaMedium
      fonts:
        - asset: fonts/FontsFree-Net-pr14.ttf

    - family: ProximaNovaBold
      fonts:
        - asset: fonts/FontsFree-Net-Proxima-Nova-Bold.otf
    - family: ProximaNovaSemiBold
      fonts:
        - asset: fonts/FontsFree-Net-Proxima-Nova-Sbold.otf
    - family: ProximaNovaRegular
      fonts:
        - asset: fonts/FontsFree-Net-proxima_nova_reg-webfont.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
